services:
  mysql:
    image: mysql:8.4
    container_name: barbearia-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3306:3306"
    volumes:
      - barbearia-mysql-data:/var/lib/mysql
  mailpit:
    image: axllent/mailpit:latest
    container_name: barbearia-mailpit
    restart: unless-stopped
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  barbearia-mysql-data: