services:
  mysql:
    image: mysql:8.4
    container_name: barbearia-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3306:3306"
    volumes:
      - barbearia-mysql-data:/var/lib/mysql

volumes:
  barbearia-mysql-data: