
spring:
  application:
    name: Sistema.Barbearia
  datasource:
    url: jdbc:mysql://localhost:3306/barbearia?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&useLegacyDatetimeCode=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root

    password: ${MYSQL_PASSWORD:your-password-here}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        type:
          preferred_insant_jdbc_type: VARCHAR
  mail:
    host: localhost
    port: 1025
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false
  flyway:
    enabled: true

